# Generated by Django 3.0.3 on 2020-03-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fragrance_Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Fragrance')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='blog.Fragrance_Favorite')),
            ],
        ),
    ]
