# Generated by Django 3.0.3 on 2020-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragrance',
            old_name='notes',
            new_name='review',
        ),
        migrations.AddField(
            model_name='fragrance',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
    ]
