# Generated by Django 3.0.3 on 2020-03-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200322_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragrance',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
