# Generated by Django 3.0.3 on 2020-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fragrance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='image',
            field=models.ImageField(blank=True, default='media/unknown.png', upload_to='images/'),
        ),
    ]
