# Generated by Django 3.0.3 on 2020-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200323_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='image',
            field=models.ImageField(blank=True, default='django_blog_site/media/unknown.png', upload_to='images/'),
        ),
    ]
