# Generated by Django 3.0.3 on 2020-03-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200323_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
