# Generated by Django 3.0.3 on 2020-03-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200323_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='image',
            field=models.ImageField(blank=True, default='media/images/unknown.png', upload_to='images/'),
        ),
    ]
