# Generated by Django 3.0.3 on 2020-03-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200323_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='image',
            field=models.ImageField(blank=True, default='C:/Users/Evan/Desktop/Django_blog_site/django_blog_site/django_blog_site/media/unknown.png', upload_to='images/'),
        ),
    ]
